# Site settings
title: Pranay Mathur
description: Budding Roboticist, Aviation Enthusiast, Avid Reader
baseurl: ""
url: "https://matnay.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pranay Mathur
user_description: Budding Roboticist, Aviation Enthusiast, Avid Reader
user_title: Undergrad
email: matnay17@gmail.com
twitter_username: matnay17
github_username:  matnay
gplus_username:  matnay17

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
