# Site settings
title: Pranay Mathur
description: Budding Roboticist, Aviation Enthusiast, Avid Reader
baseurl: "/"
url: "https://matnay.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pranay Mathur
user_description: Perception in Robotics, Computer Vision, Aerial Robotics, Deep Learning, Autonomous Vehicles and ADAS, Human-Machine Interaction
user_title: Perception Engineer at Addverb Technologies Graduate, BITS Pilani
email: matnay17@gmail.com
twitter_username: matnay17
github_username:  https://github.com/Matnay
gplus_username:  matnay17@gmail.com

# Google-analytics
google-analytics:
  id: "2150254875"

exclude: ['package.json', 'src' , 'node_modules']
